-- Project......: Employee Salaries Data Warehouse
-- File name....: datawarehouse_db_script.sql
-- Database name: datawarehouse_db
-- RDBMS........: PostgreSQL

-- DIM_DIVISAO -----------------------------------------------------

DROP TABLE IF EXISTS public.DIM_DIVISAO;

CREATE TABLE public.DIM_DIVISAO(
    SK_DIM_DIVISAO INTEGER NOT NULL,
    NK_DIM_DIVISAO INTEGER,
    DS_DIM_DIVISAO VARCHAR(100),
    DS_DIM_DIVISAO_OBSERVACAO VARCHAR(120),
    NR_DIM_DIVISAO_VERSAO INTEGER,
    DT_DIM_DIVISAO_INICIO DATE,
    DT_DIM_DIVISAO_FIM DATE,
    TS_DIM_DIVISAO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIM_DIVISAO PRIMARY KEY(SK_DIM_DIVISAO)
);

INSERT INTO public.DIM_DIVISAO(
	SK_DIM_DIVISAO, 
	NK_DIM_DIVISAO, 
	DS_DIM_DIVISAO, 
	DS_DIM_DIVISAO_OBSERVACAO, 
	NR_DIM_DIVISAO_VERSAO, 
	DT_DIM_DIVISAO_INICIO, 
	DT_DIM_DIVISAO_FIM
)
VALUES(
    0, -- SK_DIM_DIVISAO -- registro default do Apache HOP
    0, -- NK_DIM_DIVISAO
    '** NAO ENCONTRADO **', -- DS_DIM_DIVISAO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_DIVISAO_OBSERVACAO
    0, -- NR_DIM_DIVISAO_VERSAO
    '1900-01-01', -- DT_DIM_DIVISAO_INICIO 
    '2199-12-31' -- DT_DIM_DIVISAO_FIM
);                

INSERT INTO public.DIM_DIVISAO(
	SK_DIM_DIVISAO, 
	NK_DIM_DIVISAO, 
	DS_DIM_DIVISAO, 
	DS_DIM_DIVISAO_OBSERVACAO, 
	NR_DIM_DIVISAO_VERSAO, 
	DT_DIM_DIVISAO_INICIO, 
	DT_DIM_DIVISAO_FIM
)
VALUES(
    -1, -- SK_DIM_DIVISAO
    0, -- NK_DIM_DIVISAO
    '** NAO ENCONTRADO **', -- DS_DIM_DIVISAO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_DIVISAO_OBSERVACAO
    0, -- NR_DIM_DIVISAO_VERSAO
    '1900-01-01', -- DT_DIM_DIVISAO_INICIO 
    '2199-12-31' -- DT_DIM_DIVISAO_FIM
);

INSERT INTO public.DIM_DIVISAO(
	SK_DIM_DIVISAO, 
	NK_DIM_DIVISAO, 
	DS_DIM_DIVISAO, 
	DS_DIM_DIVISAO_OBSERVACAO, 
	NR_DIM_DIVISAO_VERSAO, 
	DT_DIM_DIVISAO_INICIO, 
	DT_DIM_DIVISAO_FIM
)
VALUES(
    -2, -- SK_DIM_DIVISAO
    0, -- NK_DIM_DIVISAO
    '** NAO SE APLICA **', -- DS_DIM_DIVISAO  
    'NAO SE APLICA = Quando o cruzamento entre tabela fato e tabela dimensão nao existe ou nao faz sentido.', -- DS_DIM_DIVISAO_OBSERVACAO
    0, -- NR_DIM_DIVISAO_VERSAO
    '1900-01-01', -- DT_DIM_DIVISAO_INICIO 
    '2199-12-31' -- DT_DIM_DIVISAO_FIM
);

-- DIM_CARGO -----------------------------------------------------
    
DROP TABLE IF EXISTS public.DIM_CARGO;

CREATE TABLE public.DIM_CARGO(
    SK_DIM_CARGO INTEGER NOT NULL,
    NK_DIM_CARGO INTEGER,
    DS_DIM_CARGO VARCHAR(100),
    DS_DIM_CARGO_OBSERVACAO VARCHAR(120),
    NR_DIM_CARGO_VERSAO INTEGER,
    DT_DIM_CARGO_INICIO DATE,
    DT_DIM_CARGO_FIM DATE,
    TS_DIM_CARGO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIM_CARGO PRIMARY KEY(SK_DIM_CARGO)
);

INSERT INTO public.DIM_CARGO(
	SK_DIM_CARGO,
	NK_DIM_CARGO,
	DS_DIM_CARGO,
	DS_DIM_CARGO_OBSERVACAO,
	NR_DIM_CARGO_VERSAO,
	DT_DIM_CARGO_INICIO,
	DT_DIM_CARGO_FIM
)
VALUES(
    0, -- SK_DIM_CARGO -- registro default do Apache HOP
    0, -- NK_DIM_CARGO
    '** NAO ENCONTRADO **', -- DS_DIM_CARGO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_CARGO_OBSERVACAO
    0, -- NR_DIM_CARGO_VERSAO
    '1900-01-01', -- DT_DIM_CARGO_INICIO 
    '2199-12-31' -- DT_DIM_CARGO_FIM
);

INSERT INTO public.DIM_CARGO(
	SK_DIM_CARGO,
	NK_DIM_CARGO,
	DS_DIM_CARGO,
	DS_DIM_CARGO_OBSERVACAO,
	NR_DIM_CARGO_VERSAO,
	DT_DIM_CARGO_INICIO,
	DT_DIM_CARGO_FIM

)
VALUES(
    -1, -- SK_DIM_CARGO
     0, -- NK_DIM_CARGO
    '** NAO ENCONTRADO **', -- DS_DIM_CARGO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_CARGO_OBSERVACAO
     0, -- NR_DIM_CARGO_VERSAO
    '1900-01-01', -- DT_DIM_CARGO_INICIO 
    '2199-12-31' -- DT_DIM_CARGO_FIM
);

INSERT INTO public.DIM_CARGO(
	SK_DIM_CARGO,
	NK_DIM_CARGO,
	DS_DIM_CARGO,
	DS_DIM_CARGO_OBSERVACAO,
	NR_DIM_CARGO_VERSAO,
	DT_DIM_CARGO_INICIO,
	DT_DIM_CARGO_FIM
)
VALUES(
    -2, -- SK_DIM_CARGO
     0, -- NK_DIM_CARGO
    '** NAO SE APLICA **', -- DS_DIM_CARGO  
    'NAO SE APLICA = Quando o cruzamento entre tabela fato e tabela dimensão nao existe ou nao faz sentido.', -- DS_DIM_CARGO_OBSERVACAO
     0, -- NR_DIM_CARGO_VERSAO
    '1900-01-01', -- DT_DIM_CARGO_INICIO 
    '2199-12-31' -- DT_DIM_CARGO_FIM
);

-- DIM_DEPARTAMENTO -----------------------------------------------------

DROP TABLE IF EXISTS public.DIM_DEPARTAMENTO;
	
CREATE TABLE public.DIM_DEPARTAMENTO(
    SK_DIM_DEPARTAMENTO INTEGER NOT NULL,
    NK_DIM_DEPARTAMENTO INTEGER,
    DS_DIM_DEPARTAMENTO VARCHAR(100),
    DS_DIM_DEPARTAMENTO_OBSERVACAO VARCHAR(120),
    NR_DIM_DEPARTAMENTO_VERSAO INTEGER,
    DT_DIM_DEPARTAMENTO_INICIO DATE,
    DT_DIM_DEPARTAMENTO_FIM DATE,
    TS_DIM_DEPARTAMENTO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIM_DEPARTAMENTO PRIMARY KEY(SK_DIM_DEPARTAMENTO)
);

INSERT INTO public.DIM_DEPARTAMENTO(
    SK_DIM_DEPARTAMENTO,
    NK_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO_OBSERVACAO,
    NR_DIM_DEPARTAMENTO_VERSAO,
    DT_DIM_DEPARTAMENTO_INICIO,
    DT_DIM_DEPARTAMENTO_FIM
)
VALUES(
    0, -- SK_DIM_DEPARTAMENTO -- registro default do Apache HOP
    0, -- NK_DIM_DEPARTAMENTO
    '** NAO ENCONTRADO **', -- DS_DIM_DEPARTAMENTO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_DEPARTAMENTO_OBSERVACAO
    0, -- NR_DIM_DEPARTAMENTO_VERSAO
    '1900-01-01', -- DT_DIM_DEPARTAMENTO_INICIO 
    '2199-12-31' -- DT_DIM_DEPARTAMENTO_FIM
);

INSERT INTO public.DIM_DEPARTAMENTO(
    SK_DIM_DEPARTAMENTO,
    NK_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO_OBSERVACAO,
    NR_DIM_DEPARTAMENTO_VERSAO,
    DT_DIM_DEPARTAMENTO_INICIO,
    DT_DIM_DEPARTAMENTO_FIM
)
VALUES(
    -1, -- SK_DIM_DEPARTAMENTO
     0, -- NK_DIM_DEPARTAMENTO
    '** NAO ENCONTRADO **', -- DS_DIM_DEPARTAMENTO  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_DEPARTAMENTO_OBSERVACAO
     0, -- NR_DIM_DEPARTAMENTO_VERSAO
    '1900-01-01', -- DT_DIM_DEPARTAMENTO_INICIO 
    '2199-12-31' -- DT_DIM_DEPARTAMENTO_FIM
);

INSERT INTO public.DIM_DEPARTAMENTO(
    SK_DIM_DEPARTAMENTO,
    NK_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO,
    DS_DIM_DEPARTAMENTO_OBSERVACAO,
    NR_DIM_DEPARTAMENTO_VERSAO,
    DT_DIM_DEPARTAMENTO_INICIO,
    DT_DIM_DEPARTAMENTO_FIM
)
VALUES(
    -2, -- SK_DIM_DEPARTAMENTO
     0, -- NK_DIM_DEPARTAMENTO
    '** NAO SE APLICA **', -- DS_DIM_DEPARTAMENTO  
    'NAO SE APLICA = Quando o cruzamento entre tabela fato e tabela dimensão nao existe ou nao faz sentido.', -- DS_DIM_DEPARTAMENTO_OBSERVACAO
     0, -- NR_DIM_DEPARTAMENTO_VERSAO
    '1900-01-01', -- DT_DIM_DEPARTAMENTO_INICIO 
    '2199-12-31' -- DT_DIM_DEPARTAMENTO_FIM
);

-- DIM_FUNCIONARIO -----------------------------------------------------

DROP TABLE IF EXISTS public.DIM_FUNCIONARIO;

CREATE TABLE public.DIM_FUNCIONARIO(
    SK_DIM_FUNCIONARIO INTEGER NOT NULL,
    NK_DIM_FUNCIONARIO INTEGER,
    NM_DIM_FUNCIONARIO VARCHAR(100),
    NM_DIM_FUNCIONARIO_SOBRENOME VARCHAR(100),
    DS_DIM_FUNCIONARIO_OBSERVACAO VARCHAR(120),
    NR_DIM_FUNCIONARIO_VERSAO INTEGER,
    DT_DIM_FUNCIONARIO_INICIO DATE,
    DT_DIM_FUNCIONARIO_FIM DATE,
    TS_DIM_FUNCIONARIO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIM_FUNCIONARIO PRIMARY KEY(SK_DIM_FUNCIONARIO)
);

INSERT INTO public.DIM_FUNCIONARIO(
    SK_DIM_FUNCIONARIO,
    NK_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO_SOBRENOME,
    DS_DIM_FUNCIONARIO_OBSERVACAO,
    NR_DIM_FUNCIONARIO_VERSAO,
    DT_DIM_FUNCIONARIO_INICIO,
    DT_DIM_FUNCIONARIO_FIM
)
VALUES(
    0, -- SK_DIM_FUNCIONARIO -- registro default do Apache HOP
    0, -- NK_DIM_FUNCIONARIO
    '** NAO ENCONTRADO **', -- NM_FUNCIONARIO
    '** NAO ENCONTRADO **', -- NM_SOBRENOME_FUNCIONARIO,  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_FUNCIONARIO_OBSERVACAO
    0, -- NR_DIM_FUNCIONARIO_VERSAO
    '1900-01-01', -- DT_DIM_FUNCIONARIO_INICIO 
    '2199-12-31' -- DT_DIM_FUNCIONARIO_FIM
);

INSERT INTO public.DIM_FUNCIONARIO(
    SK_DIM_FUNCIONARIO,
    NK_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO_SOBRENOME,
    DS_DIM_FUNCIONARIO_OBSERVACAO,
    NR_DIM_FUNCIONARIO_VERSAO,
    DT_DIM_FUNCIONARIO_INICIO,
    DT_DIM_FUNCIONARIO_FIM
)
VALUES(
    -1, -- SK_DIM_FUNCIONARIO
     0, -- NK_DIM_FUNCIONARIO
    '** NAO ENCONTRADO **', -- NM_FUNCIONARIO
    '** NAO ENCONTRADO **', -- NM_SOBRENOME_FUNCIONARIO,  
    'NAO ENCONTRADO = Quando a tabela fato não acha a SK na tabela dimensão.', -- DS_DIM_FUNCIONARIO_OBSERVACAO
     0, -- NR_DIM_FUNCIONARIO_VERSAO
    '1900-01-01', -- DT_DIM_FUNCIONARIO_INICIO 
    '2199-12-31' -- DT_DIM_FUNCIONARIO_FIM
);

INSERT INTO public.DIM_FUNCIONARIO(
    SK_DIM_FUNCIONARIO,
    NK_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO,
    NM_DIM_FUNCIONARIO_SOBRENOME,
    DS_DIM_FUNCIONARIO_OBSERVACAO,
    NR_DIM_FUNCIONARIO_VERSAO,
    DT_DIM_FUNCIONARIO_INICIO,
    DT_DIM_FUNCIONARIO_FIM
)
VALUES(
    -2, -- SK_DIM_FUNCIONARIO
     0, -- NK_DIM_FUNCIONARIO
    '** NAO SE APLICA **', -- NM_DIM_FUNCIONARIO
    '** NAO SE APLICA **', -- NM_DIM_FUNCIONARIO_SOBRENOME  
    'NAO SE APLICA = Quando o cruzamento entre tabela fato e tabela dimensão nao existe ou nao faz sentido.', -- DS_DIM_FUNCIONARIO_OBSERVACAO
     0, -- NR_DIM_FUNCIONARIO_VERSAO
    '1900-01-01', -- DT_DIM_FUNCIONARIO_INICIO 
    '2199-12-31' -- DT_DIM_FUNCIONARIO_FIM
);

-- DIM_CALENDAR -----------------------------------------------------

DROP TABLE IF EXISTS public.DIM_CALENDAR;

CREATE TABLE public.DIM_CALENDAR(
  ID_DIM_CALENDAR INTEGER NOT NULL,
  DT_DIM_CALENDAR DATE NOT NULL,
  NR_DIM_CALENDAR_YEAR INTEGER NOT NULL,
  NR_DIM_CALENDAR_MONTH INTEGER NOT NULL,
  NR_DIM_CALENDAR_DAY INTEGER NOT NULL,
  NR_DIM_CALENDAR_QUARTER INTEGER NOT NULL,
  NR_DIM_CALENDAR_SEMESTER INTEGER NOT NULL,
  NM_DIM_CALENDAR_MONTH VARCHAR(12) NOT NULL,
  NM_DIM_CALENDAR_WEEK_DAY VARCHAR(3) NOT NULL,
  TS_DIM_CALENDAR_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_DIM_CALENDAR PRIMARY KEY(ID_DIM_CALENDAR)
);

-- FAT_FOLHA_PAGAMENTO -----------------------------------------------------

DROP TABLE IF EXISTS public.FAT_FOLHA_PAGAMENTO;

CREATE TABLE public.FAT_FOLHA_PAGAMENTO(
  ID_FAT_FOLHA_PAGAMENTO INTEGER NOT NULL,
  ID_DIM_CALENDAR INTEGER DEFAULT 0,
  SK_DIM_FUNCIONARIO INTEGER DEFAULT 0,
  SK_DIM_DEPARTAMENTO INTEGER DEFAULT 0,
  SK_DIM_CARGO INTEGER DEFAULT 0,
  SK_DIM_DIVISAO INTEGER DEFAULT 0,
  DT_FAT_FOLHA_PAGAMENTO_SALARIO DATE,
  VL_FAT_FOLHA_PAGAMENTO_SALARIO NUMERIC(18,2), 
  TS_FAT_FOLHA_PAGAMENTO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_FAT_FOLHA_PAGAMENTO PRIMARY KEY(ID_FAT_FOLHA_PAGAMENTO)
);

