-- Project......: Employee Salaries Data Warehouse
-- File name....: stage_area_db_script.sql
-- Database name: stage_area_db
-- RDBMS........: PostgreSQL


DROP TABLE IF EXISTS public.STAGE_DEPARTAMENTO;

CREATE TABLE public.STAGE_DEPARTAMENTO(
  ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(200),
  TS_ETL_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT STAGE_DEPARTAMENTO_PK PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS public.STAGE_CARGO;

CREATE TABLE public.STAGE_CARGO(
  ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(200),
  TS_ETL_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT STAGE_CARGO_PK PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS public.STAGE_DIVISAO;

CREATE TABLE public.STAGE_DIVISAO(
  ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(200),
  TS_ETL_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT STAGE_DIVISAO_PK PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS public.STAGE_FUNCIONARIO;

CREATE TABLE public.STAGE_FUNCIONARIO(
  ID INTEGER NOT NULL,
  NOME VARCHAR(200),
  SOBRENOME VARCHAR(200),
  TS_ETL_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT STAGE_FUNCIONARIO_PK PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS public.STAGE_FOLHA_PAGAMENTO;

CREATE TABLE public.STAGE_FOLHA_PAGAMENTO(
  ID INTEGER NOT NULL,
  ID_FUNCIONARIO INTEGER,
  ID_SETOR INTEGER,
  ID_DIVISAO INTEGER,
  ID_CARGO INTEGER,
  ID_DEPARTAMENTO INTEGER,
  DT_PAGAMENTO_SALARIO DATE,
  VL_SALARIO NUMERIC(16,2),
  TS_ETL_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT STAGE_FOLHA_PAGAMENTO_PK PRIMARY KEY(ID)
);

