-- Project......: Employee Salaries Data Warehouse
-- File name....: stage_area_db_script.sql
-- Database name: stage_area_db
-- RDBMS........: PostgreSQL


DROP TABLE IF EXISTS public.STG_DEPARTAMENTO;

CREATE TABLE public.STG_DEPARTAMENTO(
  ID_STG_DEPARTAMENTO INTEGER NOT NULL,
  DS_STG_DEPARTAMENTO VARCHAR(200),
  TS_STG_DEPARTAMENTO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_STG_DEPARTAMENTO PRIMARY KEY(ID_STG_DEPARTAMENTO)
);

DROP TABLE IF EXISTS public.STG_CARGO;

CREATE TABLE public.STG_CARGO(
  ID_STG_CARGO INTEGER NOT NULL,
  DS_STG_CARGO VARCHAR(200),
  TS_STG_CARGO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_STG_CARGO PRIMARY KEY(ID_STG_CARGO)
);

DROP TABLE IF EXISTS public.STG_DIVISAO;

CREATE TABLE public.STG_DIVISAO(
  ID_STG_DIVISAO INTEGER NOT NULL,
  DS_STG_DIVISAO VARCHAR(200),
  TS_STG_DIVISAO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_STG_DIVISAO PRIMARY KEY(ID_STG_DIVISAO)
);

DROP TABLE IF EXISTS public.STG_FUNCIONARIO;

CREATE TABLE public.STG_FUNCIONARIO(
  ID_STG_FUNCIONARIO INTEGER NOT NULL,
  NM_STG_FUNCIONARIO VARCHAR(200),
  NM_STG_FUNCIONARIO_SOBRENOME VARCHAR(200),
  TS_STG_FUNCIONARIO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_STG_FUNCIONARIO PRIMARY KEY(ID_STG_FUNCIONARIO)
);

DROP TABLE IF EXISTS public.STG_FOLHA_PAGAMENTO;

CREATE TABLE public.STG_FOLHA_PAGAMENTO(
  ID_STG_FOLHA_PAGAMENTO INTEGER NOT NULL,
  ID_STG_FUNCIONARIO INTEGER,
  ID_STG_DIVISAO INTEGER,
  ID_STG_CARGO INTEGER,
  ID_STG_DEPARTAMENTO INTEGER,
  DT_STG_PAGAMENTO_SALARIO DATE,
  VL_STG_SALARIO NUMERIC(18,2),
  TS_STG_FOLHA_PAGAMENTO_CARGA TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_STG_FOLHA_PAGAMENTO PRIMARY KEY(ID_STG_FOLHA_PAGAMENTO)
);

